### ISSUE TITLE
Wheel Diameter??

### ISSUE THREAD

**Issue by erik-sk** [davidzof/wattzap-ce#104]
I just discovered this. Really like it because the video sync works, which is a problem I am having with Golden Cheetah.

But the issue I want to bring up is that in Application > Preferences > Your Information  Wheel Diameter should be Wheel Circumference. I put in my wheel diameter (584mm) and the speed was way off. Entered the circumference (2010mm) and the speed is about right. 

I couldn't find anything in your issues about this, and I am not sure how active this project is, but I thought I would mention it. 

Great app, hope it stays alive.

**Comment by davidzof** [comment]
Thanks, same problem in French and German versions. Fixed in release 2.9
