### ISSUE TITLE
Different Resistance options shown in Trainer tab if ANT+ dongle not connected

### ISSUE THREAD

**Issue by samwatling** [davidzof/wattzap-ce#83]
Example:
If I plug in my ANT+ dongle before running WattzAp, my Elite Volare Mag Speed shows options [1; 2; 3; 4; 5] in the Resistance drop-down in the Trainer panel of preferences. I have it set on 3. (This is correct)

If there's no ANT+ dongle plugged in before running WattzAp, the same trainer now shows the options [auto; 1; 2; 3; 4; 5] in the Resistance drop-down in the Trainer panel. The drop-down is set on 2 (rather than 3 as it should be).

**Comment by davidzof** [comment]
Hmmm sounds like 0 and 1 confusion for the first item in an array. Thanks for reporting.

**Comment by davidzof** [comment]
Fix: Move Auto to bottom of dropdown.

Test protocol:
Without ANT USB Dongle and using a variable resistance trainer
i. set to Auto, quit application, restart, Auto should be shown in dropdown at the bottom
ii. select a video, resistance should vary with slope angle
iii. set to a fixed value, quit and restart application, Value should be correctly set

Plug in ANT USB dongle
iv. start application, fixed value should be the same as that set in (iii) above
